image: harbor.infra.garr.it/cache/library/python:3.11

stages:
  - lint
  - publish

cache:
  paths:
    - .cache/pip
    - poetry.lock
    - pyproject.toml

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false # Disable virtual environment creation and install dependencies in the system scope
  - poetry install
  - echo "Dependencies installed, building package..."
  - poetry build
  - echo "Build done."

lint:
  stage: lint
  script:
    - poetry run ruff format .
  only:
    - main

publish_gitlab:
  stage: publish
  script:
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - echo "Repository gitlab configured ..."
    - echo "Publishing package to GitLab Package Registry"
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN} --skip-existing
    - echo "Publishing to GitLab done!"
  only:
    - main

publish_pypi:
  stage: publish
  script:
    - poetry config pypi-token.pypi ${PYPI_TOKEN}
    - echo "Repository PyPI configured ..."
    - echo "Publishing package to PyPI"
    - poetry publish
    - echo "Publishing to PyPI done!"
  only:
    - main
