name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: >
          docker build . --file Dockerfile
          --tag ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          --tag ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}:latest
